apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services
  namespace: argocd
spec:
  description: All services.
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
