apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: homelab-admins
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: leohauschild
spec:
  memberOf: [homelab-admins]
